name: flutter_survey_webview_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # Для запросов к вашему Spring Boot бэкенду
  provider: ^6.1.2 # Для управления состоянием (ваш ViewModel)



  # Добавьте эти пакеты для WebView:
  webview_flutter: ^4.13.0 
  webview_flutter_android: ^4.7.0 
  webview_flutter_wkwebview: ^3.22.0 
  url_launcher: ^6.3.0 # Для открытия ссылок в браузере

 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/survey.html
    - assets/jquery.min.js     
    - assets/survey.jquery.min.js 
    - assets/modern.min.css 

